---

- name: "uninstall activity tracking app"
  k8s:
    state: absent
    api_version: "{{ item.api_version }}"
    kind: "{{ item.kind }}"
    namespace: "{{ application_namespace }}"
    name: "{{ item.name }}"
  loop:
    - api_version: v1
      kind: service
      name: "{{ activity_tracking_service_name }}"
    - api_version: apps/v1
      kind: deployment
      name: "{{ activity_tracking_service_name }}"
    - api_version: v1
      kind: secret
      name: "{{ activity_tracking_service_name }}"
    - api_version: v1
      kind: serviceaccount
      name: "{{ activity_tracking_app_name }}"
