---

- name: "uninstall globex ui app"
  k8s:
    state: absent
    api_version: "{{ item.api_version }}"
    kind: "{{ item.kind }}"
    namespace: "{{ application_namespace }}"
    name: "{{ item.name }}"
  loop:
    - api_version: route.openshift.io/v1
      kind: route
      name: "{{ globex_ui_name }}"
    - api_version: v1
      kind: service
      name: "{{ globex_ui_name }}"
    - api_version: apps/v1
      kind: deployment
      name: "{{ globex_ui_name }}"
    - api_version: v1
      kind: serviceaccount
      name: "{{ globex_ui_app_name }}"
