---


- name: "uninstall activity tracking app"
  import_role:
    name: activity-tracking
    tasks_from: uninstall

- name: "uninstall globex ui app"
  import_role:
    name: globex-ui
    tasks_from: uninstall

- name: "uninstall catalog app"
  import_role:
    name: catalog
    tasks_from: uninstall

- name: "uninstall inventory app"
  import_role:
    name: inventory
    tasks_from: uninstall
